### PR TITLE
Province history

### PR DESCRIPTION
**Pull request by faiuwle**
Copied all the provinces from \<CK2\>/history/provinces/ that contained `west_african_pagan` and changed it to `bori` if central African culture, `a_tag_roog` if west African culture, and `amazigh` if Berber culture.  The three provinces with east African (Daju) culture were given Amazigh since otherwise we'd need an entirely different religion for them, that we don't have any information about.

### CODE REVIEW

**Comment by kaisalmon** [comment]
I tried running this in game, but it exits on "loading history" :( 
If this is to be expected, then we can just go ahead and merge this in. If not let me know

**Comment by faiuwle** [comment]
Hmm, I wasn't going to try loading it until there were actual characters of the religion to look at, but yeah, it shouldn't be crashing now.  I'm not sure, maybe it needs holy sites defined.

**Comment by kaisalmon** [comment]
It works! Theres still a lot of African pagan on the map, but it works!

**Comment by faiuwle** [comment]
Wait, there shouldn't be any more African pagan on the map after this.  Where are you seeing it?  The characters are all still African pagan, but the counties shouldn't be.

**Pull request merged**
